### ISSUE TITLE
Improve Datasource representation

### ISSUE THREAD

**Issue by ghost** [linksmart/historical-datastore#12]
<p><b>Datasource v0.5</b></p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-javascript">
{
      <span class="code-quote">"id"</span>: <span class="code-quote">"9b1921c1-b20f-496a-a127-b5a01f0a91a5"</span>,
      <span class="code-quote">"url"</span>: <span class="code-quote">"/registry/9b1921c1-b20f-496a-a127-b5a01f0a91a5"</span>,
      <span class="code-quote">"data"</span>: <span class="code-quote">"/data/9b1921c1-b20f-496a-a127-b5a01f0a91a5"</span>,
      <span class="code-quote">"resource"</span>: <span class="code-quote">"13/0/49/4/power"</span>,
      <span class="code-quote">"meta"</span>: {
<span class="code-quote">"name"</span>: <span class="code-quote">"Philip's laptop"</span>
      },
      <span class="code-quote">"connector"</span>: {
<span class="code-quote">"mqtt"</span>: {
  <span class="code-quote">"url"</span>: <span class="code-quote">"ssl:<span class="code-comment">//demo.linksmart.eu:8883"</span>,
</span>  <span class="code-quote">"topic"</span>: <span class="code-quote">"LS/v2/ZGW/linksmart-philip/senml"</span>,
  <span class="code-quote">"qos"</span>: 1
}
      },
      <span class="code-quote">"retention"</span>: <span class="code-quote">"1w"</span>,
      <span class="code-quote">"aggregation"</span>: [
{
  <span class="code-quote">"id"</span>: <span class="code-quote">"4efaf6fb"</span>,
  <span class="code-quote">"interval"</span>: <span class="code-quote">"1m"</span>,
  <span class="code-quote">"data"</span>: <span class="code-quote">"/aggr/4efaf6fb/9b1921c1-b20f-496a-a127-b5a01f0a91a5"</span>,
  <span class="code-quote">"aggregates"</span>: [
    <span class="code-quote">"mean"</span>
  ],
  <span class="code-quote">"retention"</span>: ""
}
      ],
      <span class="code-quote">"type"</span>: <span class="code-quote">"<span class="code-keyword"><span class="code-object">float</span></span>"</span>,
      <span class="code-quote">"format"</span>: <span class="code-quote">"application/senml+json"</span>
}
</pre>
</div></div>
<p><b>Problems</b></p>
<ul>
	<li>two identifiers (id and resource) needed during different operations.</li>
	<li>resource is the name attribute in SenML</li>
	<li>"format" carries no important information (it's the same for all)</li>
	<li>url, data, aggr.data are shows as absolute paths but in fact they are relative to the public endpoint.</li>
</ul>

<i>[LS-447] created by tavakoli</i>

**Comment by dschowta** [comment]
The new format is as follows:
```
     {
      "name": "c5/1/kitchen/coffee-tablet/power",
      "source": {
        "type": "MQTT",
        "url": "tcp://mqtt.eclipse.org:1883",
        "topic": "c5/1/kitchen/coffee-tablet/power"
      },
      "dataType": "float",
      "meta": null,
      "retain": {
         "min":"1w",
         "max":"1y"
      }
```

**Comment by dschowta** [comment]
representation is updated from V1.x.x
