### ISSUE TITLE
Road to HDS v1

### ISSUE THREAD

**Issue by ghost** [linksmart/historical-datastore#13]
<p>Historical Datastore should be improved to support expected use-cases with simple and pragmatic APIs.</p>

<p> </p>

<p>Use cases:</p>
<ul>
	<li>Low dimensional time-series storage and retrieval <img class="emoticon" src="https://boards.linksmart.eu/images/icons/emoticons/check.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>High dimensional time-series storage and retrieval</li>
	<li>Log storage and retrieval</li>
	<li>Lightweight storage on IoT devices by using embedded DBs such as Leveldb, Boltdb, Sqlite</li>
</ul>

<p>Features:</p>
<ul>
	<li>Retention <img class="emoticon" src="https://boards.linksmart.eu/images/icons/emoticons/check.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>Simple aggregation (persistent) <img class="emoticon" src="https://boards.linksmart.eu/images/icons/emoticons/check.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>HTTP API <img class="emoticon" src="https://boards.linksmart.eu/images/icons/emoticons/check.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>MQTT connector <img class="emoticon" src="https://boards.linksmart.eu/images/icons/emoticons/check.png" height="16" width="16" align="absmiddle" alt="" border="0"/></li>
	<li>Annotation</li>
	<li>Query with mathematical functions</li>
</ul>

<i>[LS-446] created by tavakoli</i>

**Comment by dschowta** [comment]
Closing this as it is converted as milestone
