### ISSUE TITLE
Extend TLS support in HDS MQTT connector

### ISSUE THREAD

**Issue by ghost** [linksmart/historical-datastore#25]
<p>Todo:</p>
<ul>
	<li>Self-signed CA</li>
	<li>Client key</li>
	<li>Client cert</li>
</ul>

<p>Sample code: <a href="https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/ssl/main.go" class="external-link" rel="nofollow">https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/ssl/main.go</a></p>
<i>[LS-307] created by tavakoli</i>

**Comment by farshidtz** [comment]
Implemented 1839e8a29a62846c76714300dc48d4fe3bb52e48, a069a484d97af943a5be3f7c4bd0a2fd09327f40
Validation #55 is still missing.
