### ISSUE TITLE
Turn aggregations into SenML

### ISSUE THREAD

**Issue by linksmart-code** [linksmart/historical-datastore#4]
<p>How it is now:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
{
    <span class="code-quote">"bn"</span>: <span class="code-quote">"string"</span>,
    <span class="code-quote">"bu"</span>: <span class="code-quote">"string"</span>,
    <span class="code-quote">"bts"</span>: <span class="code-quote">"<span class="code-object">int</span>"</span>,
    <span class="code-quote">"bte"</span>: <span class="code-quote">"<span class="code-object">int</span>"</span>,
    <span class="code-quote">"e"</span>: [
{
    <span class="code-quote">"n"</span>: <span class="code-quote">"string"</span>,
    <span class="code-quote">"ts"</span>: <span class="code-quote">"<span class="code-object">int</span>"</span>,
    <span class="code-quote">"te"</span>: <span class="code-quote">"<span class="code-object">int</span>"</span>,
    <span class="code-quote">"mean"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>,
    <span class="code-quote">"stddev"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>,
    <span class="code-quote">"sum"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>,
    <span class="code-quote">"min"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>,
    <span class="code-quote">"max"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>,
    <span class="code-quote">"median"</span>: <span class="code-quote">"<span class="code-object">float</span>"</span>
}
    ]
}
</pre>
</div></div>
<p>The aggregate could be instead part of the name. "te" is not needed. The rest can fit into SenML.</p>
<i>[LS-485] created by tavakoli</i>

**Comment by dschowta** [comment]
Aggregartions are not supported. When the support is added, this shall be following SenML
