### ISSUE TITLE
Internal aggreagation support

### ISSUE THREAD

**Issue by dschowta** [linksmart/historical-datastore#54]
Supporting aggregation function in HDS:

- Should support API based aggregation (Separate API for creation of aggregations)
- Support basic aggregations such as 
  - Mean
  - Sum
  - Last value
  - custom with a go or python code
- This aggregation should be triggered via
  - Periodic (cron based)
  - Data based (triggered whenever a new data point is inserted)

**Comment by farshidtz** [comment]
Closing in favour of #82.
