### ISSUE TITLE
Support WoT Things description for representing data

### ISSUE THREAD

**Issue by dschowta** [linksmart/historical-datastore#56]
This issue is created to support Web of things  Things description specification for storage of the metadata.
Example
```JSON
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTTemp-1234",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"],
    "base": "/data/",
    "properties": {
        "source" : { 
            "type": "float",
            "forms": [{
		"href": "https://gw1.iot/status", 
	         "contentType": "application/senml+json",
		 "op": ["readproperty", "writeproperty"],
		 "security": ["basic_sc"]
	    }],
        },
        "storage" : { 
	   "readOnly" : true,
            "type": "float",
            "forms": [{"href": "/data/urn:dev:ops:32473-WoTTemp-1234","security": ["basic_sc"]}]
        }
    }
}

```
In the above example. `properties/source` property represents the original device that produced the data. On the other hand, `properties/storage` represents the data stored as part of historical datastore. 
The sample senml:
```JSON
[
  {"bn":"urn:dev:ops:32473-WoTTemp-1234","bu":"Cel","t":1.276020076e+09, "v":20},
  {"t":1.276020091e+09, "v":23.5},
]
```

**Comment by farshidtz** [comment]
Since WoT is meant to describe how to interact with things rather than how to store their data, it may be better to keep it out of HDS. We can instead implement a WoT registry as a standalone component (perhaps as the new Resource Catalog API) with Thing Descriptions including properties of DGW and HDS endpoints (as the example above).

The separation of concern helps in:
- keeping HDS codebase and functionality to storage only
- independent development and deployment of WoT registry and HDS
- use of WoT registry without storage functionalities

**Comment by dschowta** [comment]
It is still not clear. which of the following are you proposing?
- No registry for HDS at all. An independent Resource Catalog (RC) will store all the metadata in WoT TD format. 
- There is a registry for HDS which stores HDS data in WOT format + there is a separate Resource Catalog that stores all the resources including HDS streams.
- There is a registry for HDS which stores HDS data in non-standard format (Current state) + there is a separate Resource Catalog that stores all the resources including HDS streams.

**Comment by farshidtz** [comment]
Last option.

**Comment by dschowta** [comment]
Okay. makes sense. closing the issue.  We need a strategy for a registrator which takes care of registration of new streams in HDS in the Resource Catalog and does the bookkeeping in order to keep the HDS Registry and the RC registry consistent with each other.
