### ISSUE TITLE
Confusing time query parameters

### ISSUE THREAD

**Issue by farshidtz** [linksmart/historical-datastore#58]
`from` and `to` query parameters become counter-intuitive when querying records descendingly.  

In the example below, `to` is actually the upper limit in the response, but one could think of it as the lower limit:
/data/power?&perPage=1000&sort=desc&to=2020-02-21T15:04:13Z

We could instead use comparison operators for time: `lt`, `lte`, `gt`, `gte`

**Comment by dschowta** [comment]
d5c5e3917987761f0ca0372267e7a0b22ba15473 and dda8c05d0914a4b9d6c72aced5fe34e83d5ecd7a to fix integration test failures
