### ISSUE TITLE
Data types and attributes

### ISSUE THREAD

**Issue by aminrahman** [linksmart/historical-datastore#63]
Hello I have some issues with the data types and attributes of data stored in HDS:
1. What is the "t" key in the data json from data stores? Is it the time? how can I change it to the time format?
2. in each GET request for /data/DsName, I get a json consisting some attributes like safelink and the number of values. What is this safe link and how can I increase the number of values? Is it always 1000 and I lose the ones over this number?
3. How can I store data with other data types? I use the float data type that i saw in the hello world tutorial. But what about String? should I use char? is it the same as data types for SQL? Something specific for sqlite? Or for the LinkSmart HDS itself?
4. Can I store more columns than just value? for example, can I make a json with key values like: value, time, date, status...?

**Comment by dschowta** [comment]
Dear @aminrahman, 
We are glad that you are using HDS for the data storage. 
Below I try to answer your questions:
> What is the "t" key in the data json from data stores? Is it the time? how can I change it to the time format?

JSON format follows [RFC 8428 (SenML)] (https://tools.ietf.org/html/rfc8428#section-5). as you already identified, `t` is time field relative to UNIX Epoch. More details can be found in the same RFC in section [4.5.3](https://tools.ietf.org/html/rfc8428#section-4.5.3). 

Changing to the time format depends on the language your client uses. But if you want to  validate manually, you can use [epochconverter](https://www.epochconverter.com/).

**Comment by dschowta** [comment]
>in each GET request for /data/DsName, I get a json consisting some attributes like safelink and the number of values. What is this safe link and how can I increase the number of values? Is it always 1000 and I lose the ones over this number?

You do not lose the ones over this number. In order, not to overwhelm both the client and the server, we used 1000 as the maximum number of values to be returned per request. You can use pagination to get the next pages
you can follow `nextlink` field to get the next page.

for example if your first response contains:
``` json
{
  "selfLink": "/data/terrace/temperature?&perPage=1000&sort=desc&to=2020-04-14T10:52:59Z&page=1",
  "data": [
    {
      "n": "terrace/temperature",
      "u": "Cel",
      "t": 1583861337.5185657,
      "v": 20.770862545133333
    },
    {
      "n": "terrace/temperature",
      "u": "Cel",
      "t": 1583861332.5185533,
      "v": 19.72179400877726
    } 
    ... //Some more skipped entries
    {
      "n": "terrace/temperature",
      "u": "Cel",
      "t": 1583856342.5184987,
      "v": 19.782858079360853
    }
  ],
  "took": 0.004789429,
  "nextLink": "/data/terrace/temperature?&perPage=1000&sort=desc&to=2020-04-14T10:52:59Z&page=2"
}
```
Here you can see the "nextlink" field `  "nextLink": "/data/terrace/temperature?&perPage=1000&sort=desc&to=2020-04-14T10:52:59Z&page=2"` which explicitly specifies "page" parameter with value 2. 

In addition you can use `count=true` in the query parameters to get the total count (e.g. GET /data/terrace/temperature?count=true). Then you will get the json response with `count` field which specifies the total number of records matching the query.

**Comment by dschowta** [comment]
> How can I store data with other data types? I use the float data type that i saw in the hello world tutorial. But what about String? should I use char? is it the same as data types for SQL? Something specific for sqlite? Or for the LinkSmart HDS itself?

[This example in RFC](https://tools.ietf.org/html/rfc8428#section-5.1.5) shows data for other datatypes. 
As specified there you can have 

+ number: 
    example registry: 

    ``` json
        {
        "name": "urn:dev:ow:10e2073a01080063:temp",
        "dataType": "float",
        "unit": "Cel",
        }
    ```
    example data: 

    ```json
    {
        "n":"urn:dev:ow:10e2073a01080063:temp",
        "u":"Cel", 
        "t": 1583856342.5184987,
        "v":23.1
    }
    ```

+ string:

    example registry: 

    ``` json
        {
        "name": "urn:dev:ow:10e2073a01080063:label",
        "dataType": "string",
        }
    ```
    example data:

    ```json
    {
        "n":"urn:dev:ow:10e2073a01080063:label",
        "t": 1583856342.5184987,
        "vs":"Machine Room"
    }
    ```

+ boolean: 

    example registry: 

    ``` json
        {
        "name": "urn:dev:ow:10e2073a01080063:open",
        "dataType": "bool",
        }
    ```
    example data:

     ```json
     {
         "n":"urn:dev:ow:10e2073a01080063:open", 
         "t": 1583856342.5184987,
         "vb":false
    }
     ```

+ Any binary data (preferably base64 encoded): 

    example registry: 

    ``` json
        {
        "name": "urn:dev:ow:10e2073a01080063:open",
        "dataType": "data",
        }
    ```

    example data:

     ```json
     {"n":"urn:dev:ow:10e2073a01080063:nfc-reader","vd":"aGkgCg"}
     ```

**Comment by dschowta** [comment]
> Can I store more columns than just value? for example, can I make a json with key values like: value, time, date, status...?

No. You have to create multiple registry entries for storing `value` and `status`. Instead. But you can add them together in a single request.
e.g.
1. create two registry entry for `value` and `status`
    ```shell 
    $curl -X POST -i  http://localhost:8085/registry/  -d \
    '{ "name": "dummy/location1/sensor1/value",  "datatype": "float" }'
    $curl -X POST -i  http://localhost:8085/registry/  -d \
    '{ "name": "dummy/location1/sensor1/status",  "datatype": "string" }'
    ```
2. Upload the data for both the sensors in one shot
    ```bash     
    $curl -X POST \
    http://localhost:8085/data/ \
    -H 'content-type: application/senml+json' \
    -d '[{"n":"dummy/location1/sensor1/value","v":24.5},{"n":"dummy/location1/sensor1/status","vs":"active"} ]'
    ```
3. Fetch the data for both the sensors at once:
    ```bash
    $curl http://localhost:8085/data/dummy/location1/sensor1/value,dummy/location1/sensor1/status
    ```
    The following data will be retrieved:

    ```json
    {
        "selfLink": "/data/dummy/location1/sensor1/value,dummy/location1/sensor1/status?&perPage=1000&sort=desc&to=2020-04-14T10:52:59Z&page=1",
        "data": [
            {
            "n": "dummy/location1/sensor1/value",
            "t": 1583861332.5185533,
            "v": 20.770862545133333
            },
            {
            "n": "dummy/location1/sensor1/status",
            "t": 1583861332.5185533,
            "vs":"active"
            } 
        ],
        "took": 0.004789429,
    }
    ```

**Comment by aminrahman** [comment]
Thank you so much! This was great! I will use these instructions :)

**Comment by aminrahman** [comment]
Dear @dschowta ,
I used these instructions to get data from my data stores.
There are some problems though:
1 - The selfLink and nextLink in my response do not contain <code>page=1</code> and <code>page=2</code> parts. I am sure there is more data there. Because the epoch time shows only the data from April 20, but my sensors have been recording data from April 17.
2 - When I add the <code>count=true</code> part to my link, I do not get any <code>count</code> attribute specifying number of recorded data.

My request link is:
<code>http://0.0.0.0:8085/data/LightDS?count=true</code>

The response is:
<code>
{"selfLink":"/data/LightDS?\u0026perPage=1000\u0026sort=desc\u0026to=2020-04-20T19:55:10Z","data":[{"n":"LightDS","t":1587408466.6104386,"vs":"72.26,0,Local"},{"n":"LightDS","t":1587408435.4391153,"vs":"63.74,5,Local"},{"n":"LightDS","t":1587408398.8621585,"vs":"67.17,5,Local"},{"n":"LightDS","t":1587408363.7249608,"vs":"62.6,5,Local"},{"n":"LightDS","t":1587408321.5246763,"vs":"62.65,5,Local"},
///Some other data.....
{"n":"LightDS","t":1587374634.578906,"vs":"47.26,10,Local"},{"n":"LightDS","t":1587374601.6923134,"vs":"73.83,0,Local"},{"n":"LightDS","t":1587374566.2391346,"vs":"80.97,5,Local"},{"n":"LightDS","t":1587374521.6774826,"vs":"45.53,10,Local"},{"n":"LightDS","t":1587374487.025453,"vs":"75.17,0,Local"}],"took":0.013751979,"nextLink":"/data/LightDS?\u0026perPage=1000\u0026sort=desc\u0026to=2020-04-20T09:20:52Z"}
</code>

**Comment by dschowta** [comment]
Dear @aminrahman ,
This looks like you are working on a older version (before 16daa02f4562735d0a3eb186a157bf3b84e93174) of HDS. Could you try on the latest version? 
You can get the binaries from [the github releases](https://github.com/linksmart/historical-datastore/releases). Or if you are using docker  from [the docker hub](https://hub.docker.com/r/linksmart/hds/tags). 

**Caution:** Please be aware of the change in [config file](https://github.com/linksmart/historical-datastore/commit/a2c2c37c39055d93f2e95933087246c35132782b#diff-7b3d7d9a0fbf191ce00d13e438cb6d03)!

Since we moved from Boltdb to sqlite recently , and if you were using boltdb so far, you can migrate the existing data from old HDS (with boltdb) to the new instance (with sqlite) by running two Historical datastores (old and new with different ports or in different computers) simultaneously and running the [command line tool called hds-migrator](https://github.com/linksmart/hds-migrator). 

Sorry for the inconvenience.

**Comment by aminrahman** [comment]
Dear @dschowta 
I am using HDS on my raspberry pi computers. Thanks to @farshidtz I had been informed about the arm build of HDS (which I am very thankful for) but I was reluctant to replace it. Now that you say my problem is related to the version of the HDS I use, I downloaded historical-datastore-linux-arm (v1.0.0-beta.8). I have  some problems though:
1- I start my server using <code>./historical-datasoter-linux-arm -conf config.json</code> and it starts perfectly. But when I send a POST request to create a new registry, I get 500 error which as you know, is an <code>Internal Server Error</code>. Then I tried the prev. version (v1.0.0-beta.7) but I get a new error:
</b>
<code>
Config File: All ServiceCatalog entries must have either endpoint or a discovery flag defined
panic: Config File: All ServiceCatalog entries must have either endpoint or a discovery flag defined
goroutine 1 [running]:
log.Panicf(0x4e2b26, 0x10, 0x2cc7eec, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.14.1/x64/src/log/log.go:358 +0x94
main.main()
	/home/runner/work/historical-datastore/historical-datastore/main.go:71 +0x36c
</code>
</b>
What should I do? Is there any stable version?
</b>
2-In another <a href="https://github.com/linksmart/historical-datastore/issues/59">issue</a> @farshidtz taught me how to persist my data after the server gets down and you added the instructions to <a href="https://github.com/linksmart/historical-datastore">README.md</a> of the project. My question is, how to persist data when I'm using the arm version of HDS? Should I still use the same -v flag?

**Comment by farshidtz** [comment]
Hi @aminrahman.

Please use the latest version and share the log outputs of HDS after getting the Internal Server Error.

If you use the [sample config file](https://github.com/linksmart/historical-datastore/blob/master/sample_conf/historical-datastore.json), the data will persist at `./hds` as set in `registry.backend.dsn` and `data.backend.dsn`. The `-v` flag is for persisting Docker Container data.

**Comment by aminrahman** [comment]
Dear @farshidtz,
Yes that is the exact same error I get.
Thank you.

Error I get:
<code>
{
"code":500,
"message":"Error writing data to the database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
}
</code>

**Comment by farshidtz** [comment]
The issue is more complicated than I expected affecting binaries for all platforms. We'll have to find a solution replacing the current cross-compilation approach.

For the time being, please try to use the following and let me know how it goes: https://github.com/linksmart/historical-datastore/releases/download/v1.0.0-beta.8/historical-datastore-linux-arm-issue63

**Comment by aminrahman** [comment]
Dear @farshidtz 
I tried to use the temp version you provided. I get this error:
<pre><code>
./hds-63: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./hds-63)
</pre></code>

**Comment by farshidtz** [comment]
> Dear @farshidtz
> I tried to use the temp version you provided. I get this error:
> 
> ```
> 
> ./hds-63: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./hds-63)
> ```

Seems like the dependencies are missing on your device. Please try the following which has staticly linked libraries:
https://github.com/linksmart/historical-datastore/releases/download/v1.0.0-beta.8/historical-datastore-linux-arm-static-issue63

**Comment by aminrahman** [comment]
> > Dear @farshidtz
> > I tried to use the temp version you provided. I get this error:
> > ```
> > 
> > ./hds-63: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./hds-63)
> > ```
> 
> Seems like the dependencies are missing on your device. Please try the following which has statically linked libraries:
> https://github.com/linksmart/historical-datastore/releases/download/v1.0.0-beta.8/historical-datastore-linux-arm-static-issue63

Thank you so much. It works. If any new conflict or error happened I will report it here.

**Comment by aminrahman** [comment]
Hello,
I have a problem using HDS. Let's say my devices are working for a while and have collected 1400 records of temperature (I know this number from sending a request with <code>count=true</code> parameter). The algorithm I use to collect data and save in a file is that I send the first request normally and get the first 1000 records. Now if the <code>nextLink</code> is null, the algorithm ends. But if there is another page the <code>nextLink</code> will not be null. Therefore, I put the requests in a <code>do-while(nextLink != null)</code> loop. It works but the problem is that when I check the data queried from datastores, the number of data is always a factor of 1000. For example, when it is 1400, the number of data is 2000! I code in Java so I bring my code here:
<pre><code>
private static void getData(String dbName, String fileName) {

        String initialResult = RestClient.getInstance().getDataFromDS(dbName);// gets first page data

        StringBuilder finalResult = new StringBuilder();

        // parsing initialResult
        Object initialObject = null;
        try {
            initialObject = new JSONParser().parse(initialResult);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // typecasting initialObject to JSONObject
        JSONObject initialJsonObject = (JSONObject) initialObject;

        // getting data
        JSONArray initialDataJsonArray = (JSONArray) initialJsonObject.get("data");

        for (Object o : initialDataJsonArray) {
            JSONObject djo = (JSONObject) o;
            String n = (String) djo.get("n");
            double t = (double) djo.get("t");
            String vs = (String) djo.get("vs");
            finalResult.append(n).append(",").append(t).append(",").append(vs).append("\n");
        }

        // getting nextLink
        String nextLink = (String) initialJsonObject.get("nextLink");

        if (nextLink != null) {
            boolean hasNext = true;
            String loopResult;
            Object loopObject;
            JSONObject loopJsonObject;
            JSONArray loopData;
            int i = 2;
            do {
                loopResult = RestClient.getInstance().getPaginatedDataFromDS(dbName, i); //gets data from page i
                if (!loopResult.equals(Contract.IOEXEPTION_CODE)) {
                    try {
                        loopObject = new JSONParser().parse(loopResult);
                        loopJsonObject = (JSONObject) loopObject;
                        nextLink = (String) loopJsonObject.get("nextLink");
                        loopData = (JSONArray) initialJsonObject.get("data");
                        for (Object o : loopData) {
                            JSONObject djo = (JSONObject) o;
                            String n = (String) djo.get("n");
                            double t = (double) djo.get("t");
                            String vs = (String) djo.get("vs");
                            finalResult.append(n).append(",").append(t).append(",").append(vs).append("\n");
                        }
                        i++;
                        System.out.println("page: " + i + " and nextLink is: " + nextLink);
                        if (nextLink == null)
                            hasNext = false;
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }

            } while (hasNext);
        }


        try {
            BufferedWriter out = new BufferedWriter(new FileWriter(fileName));
            out.write(String.valueOf(finalResult));
            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
</code></pre>

**Comment by dschowta** [comment]
Dear @aminrahman,
I tested the my version of HDS  and it works as expected. (Try out once with your version too over the browser/postman/curl)
Looks like there is a copy paste error in your code. i.e. you used `initialJsonObject` instead of `loopJsonObject` while retrieving the data from json object. 
as below:
```
if (!loopResult.equals(Contract.IOEXEPTION_CODE)) {
                    try {
                        loopObject = new JSONParser().parse(loopResult);
                        loopJsonObject = (JSONObject) loopObject;
                        nextLink = (String) loopJsonObject.get("nextLink");
                        ************************************************
                        //This like causes a problem :
                         // loopData = (JSONArray) initialJsonObject.get("data");
                        //replace it with the following line:
                         loopData = (JSONArray) loopJsonObject.get("data");
                       ******************************************************
                      
                        for (Object o : loopData) {
                            JSONObject djo = (JSONObject) o;
                            String n = (String) djo.get("n");
                            double t = (double) djo.get("t");
                            String vs = (String) djo.get("vs");
                            finalResult.append(n).append(",").append(t).append(",").append(vs).append("\n");
                        }
                        i++;
                        System.out.println("page: " + i + " and nextLink is: " + nextLink);
                        if (nextLink == null)
                            hasNext = false;
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }
```
Let us know if that solves or not

**Comment by aminrahman** [comment]
Dear @dschowta,
Yes your edit solved my problem. I'm sorry you had to check that even though it has nothing to do with HDS. I have to develop my code in an IDE in my laptop and run my codes on my R.Pi's, making it hard to debug. Anyway, thanks a lot for your time and effort :)
