### ISSUE TITLE
count is not working

### ISSUE THREAD

**Issue by dschowta** [linksmart/historical-datastore#66]
Dear @dschowta ,
I used these instructions to get data from my data stores.
There are some problems though:
1 - The selfLink and nextLink in my response do not contain <code>page=1</code> and <code>page=2</code> parts. I am sure there is more data there. Because the epoch time shows only the data from April 20, but my sensors have been recording data from April 17.
2 - When I add the <code>count=true</code> part to my link, I do not get any <code>count</code> attribute specifying number of recorded data.

My request link is:
<code>http://0.0.0.0:8085/data/LightDS?count=true</code>

The response is:
<code>
{"selfLink":"/data/LightDS?\u0026perPage=1000\u0026sort=desc\u0026to=2020-04-20T19:55:10Z","data":[{"n":"LightDS","t":1587408466.6104386,"vs":"72.26,0,Local"},{"n":"LightDS","t":1587408435.4391153,"vs":"63.74,5,Local"},{"n":"LightDS","t":1587408398.8621585,"vs":"67.17,5,Local"},{"n":"LightDS","t":1587408363.7249608,"vs":"62.6,5,Local"},{"n":"LightDS","t":1587408321.5246763,"vs":"62.65,5,Local"},
///Some other data.....
{"n":"LightDS","t":1587374634.578906,"vs":"47.26,10,Local"},{"n":"LightDS","t":1587374601.6923134,"vs":"73.83,0,Local"},{"n":"LightDS","t":1587374566.2391346,"vs":"80.97,5,Local"},{"n":"LightDS","t":1587374521.6774826,"vs":"45.53,10,Local"},{"n":"LightDS","t":1587374487.025453,"vs":"75.17,0,Local"}],"took":0.013751979,"nextLink":"/data/LightDS?\u0026perPage=1000\u0026sort=desc\u0026to=2020-04-20T09:20:52Z"}
</code>

_Originally posted by @aminrahman in https://github.com/linksmart/historical-datastore/issues/63#issuecomment-616780478_

**Comment by dschowta** [comment]
answered [here](https://github.com/linksmart/historical-datastore/issues/63#issuecomment-617021505)

**Comment by farshidtz** [comment]
Answered here: https://github.com/linksmart/historical-datastore/issues/63#issuecomment-617021505

**Comment by dschowta** [comment]
answered in [#63 comment](https://github.com/linksmart/historical-datastore/issues/63#issuecomment-617021505)
