### ISSUE TITLE
Avoid idempotent POST method for registry

### ISSUE THREAD

**Issue by dschowta** [linksmart/historical-datastore#69]
Currently the post request is idempotent. i.e. Multiple POST requests with the same content has the same effect as the effect of a single request. 
```bash

curl --location --request POST 'http://localhost:8085/registry/' \
--header 'Content-Type: application/json' \
--data-raw '{
	"name": "terrace/temperature",
	"datatype": "float",
	"unit": "C"
}'

```
creates a new registry for `terrace/temperature` with `201 created`. Further POST requests do not create the same object, instead, the client gets `409 conflict`. 

This is does not follow the HTTP semantics mentioned in [RFC 7231](https://tools.ietf.org/html/rfc7231) 
` A request method is considered "idempotent" if the intended effect on
   the server of multiple identical requests with that method is the
   same as the effect for a single such request.  Of the request methods
   defined by this specification, PUT, DELETE, and safe request methods
   are idempotent.` ([section 4.2.2.  Idempotent Methods](https://tools.ietf.org/html/rfc7231#section-4.2.2))

Therefore, we can opt for the following approach:

-  If the client does not want to provide the senml name, it uses POST method and gets a [unique senml name](https://tools.ietf.org/html/rfc8428#section-4.5.1) for the record. and the new location shall be provided in the location header of the response (201 created).
-  If the client knows what the senml name is, it uses PUT method with "name" field. and gets 201 created on the response.

**Comment by farshidtz** [comment]
This article nicely explains http and restful design concepts (see post and put): https://restfulapi.net/http-methods/#post

**Comment by dschowta** [comment]
Deprecated post for the registry. PUT is used for creation instead. PUT returns 201 created when the registry entry is newly created. 200 ok when updated
