### ISSUE TITLE
Supporting hierarchy in data streams

### ISSUE THREAD

**Issue by dschowta** [linksmart/historical-datastore#74]
Data streams can be hierarchical. For example, 
`de:Fraunhofer:fit:building1:kitchen` can return the data streams which are under it, such as 

`de:Fraunhofer:fit:building1:kitchen:lamp`, `de:Fraunhofer:fit:building1:kitchen:refrigerator:power`, `de:Fraunhofer:fit:building1:kitchen:temperature`

These relations can be part of the data stream element by adding fields to the children such as `parent`

an example:
```javascript
{
	"name": "de:Fraunhofer:fit:building1:kitchen:lamp",
	"datatype": "boolean",
        "parent": "de:Fraunhofer:fit:building1:kitchen"
}
```

**Comment by dschowta** [comment]
**Note**: in order to avoid the misuse of the parent-child relationships, the "parent" field should be a prefix of the "name" field.  Other strings should not be allowed

**Comment by farshidtz** [comment]
Include meta data inside data api for knowing the dimensions that may come in follow up pages:
```json
{
  "items": [  ], // results
  "series": [ "a/b/c" ]
}
```


```json
{
  "items": [  ], // results
  "links": [
      {
          "rel": "self",
          "href": "",
      },
      {
          "rel": "next",
          "href": "",
      },
      {
          "rel": "serie1",
          "href": "",
      },
      {
          "rel": "serie2",
          "href": "",
      },
      ...
  ]
}
```

**Comment by farshidtz** [comment]
We could also merge registry and data information models: 

GET /data/de:Fraunhofer:fit:building1:kitchen:lamp
```json
{
  "items": [  ], // results
  "metadata": [
      {
          "name": "de:Fraunhofer:fit:building1:kitchen:lamp",
          "dataType": "float",
      }
  ]
}
```

GET /data/many/prefix/equals/de:Fraunhofer:fit:
```json
{
  "items": [  ], // results
  "metadata": [
      {
          "name": "de:Fraunhofer:fit:building1:kitchen:lamp",
          "dataType": "float",
      },
      {
          "name": "de:Fraunhofer:fit:building1:kitchen:fan",
          "dataType": "float",
      }
  ]
}
```

**Comment by dschowta** [comment]
This looks good. The heirarchical querying should not be enabled by default in order to avoid load on the server. Instead the client can query the streams the way it is done in registry with operations namely: `prefix`, `suffix`, `contains`, `equals`. for example,
`http:localhost:8085/data/de:Fraunhofer:fit:building1:kitchen?prefix` or `http:localhost:8085/data/de:Fraunhofer:fit:building1:kitchen?suffix` etc. 
The operation equals, is the operation which is performed by default where only exactly matching time series are returned.

**Comment by farshidtz** [comment]
Since the URL has no size limit by specification, we can assume that the client can query multiple streams by providing their IDs inside the URL without facing issues.

For convenience, we may add a "data" link inside registry with a prepared URL to query all (or filtered) streams.
