### ISSUE TITLE
Add aggregation support in data API

### ISSUE THREAD

**Issue by farshidtz** [linksmart/historical-datastore#82]
Query parameter:
groupBy=aggregator,interval

where:
- `aggregator` is the aggregation function name
- `interval` is the Go duration string. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"

Supported aggregation functions:
- [x] mean
- [x] min
- [x] max
- [ ] stddev

**Comment by dschowta** [comment]
Further aggregations such as Stdev, median can be added based on need basis.  More details to achieve it can be found in [go-sqlite3 README](https://github.com/mattn/go-sqlite3#extension-functionsc-from-sqlite3-contrib). 
Cross-compilation of the extension file might take some efforts.
